// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func Inject() *Container {
	container := &Container{}
	return container
}

// wire.go:

type Container struct {
}
